<a href="https://colab.research.google.com/github/alondra-alvarez/Excel-Caso-Practico/blob/main/Caso_practico_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analisis de Tuberculosis

**Planteamiento**  

Usted trabaja para la Organización Mundial de la Salud como analista de
información. El consejo directivo se reunirá para revisar los datos más recientes de casos de tuberculosis.  

Los datos han llegado con la información más reciente y necesita prepararlos
para mostrar la información a los líderes de la organización.
El objetivo de la junta es entender la situación actual de tuberculosis, y las
tendencias por región e identificar países que han sido casos de éxito y aquellos que necesiten mayor apoyo con la gestión de la enfermedad.  

Tenga en mente las metas de la ONU para terminar con la Tuberculosis para
2025:
* Reducción en la tasa de incidencia del 50% 2015 vs 2025.
* Reducción en 75% el número de muertes 2015 vs 2025

In [1]:
from google.colab import drive
import pandas as pd
import numpy as np

drive.mount('/content/drive')

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

Mounted at /content/drive

In [2]:
who = pd.read_csv("/content/drive/MyDrive/google_colab/who.csv")
population = pd.read_csv("/content/drive/MyDrive/google_colab/population.csv")

In [3]:
who.head()

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,Afghanistan,AF,AFG,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,AFG,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,AFG,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
population.head()

       country  year  population
0  Afghanistan  1995    17586073
1  Afghanistan  1996    18415307
2  Afghanistan  1997    19021226
3  Afghanistan  1998    19496836
4  Afghanistan  1999    19987071

#Investigacion previa sobre el tema

**Que es la tuberculosis**  
La tuberculosis (TB) es una enfermedad infecciosa causada por una bacteria llamada Mycobacterium tuberculosis. Afecta principalmente a los pulmones, aunque también puede atacar otras partes del cuerpo como los riñones, la columna vertebral o el cerebro.

**Causas de la tuberculisis**  
La causa principal es la infección por la bacteria Mycobacterium tuberculosis, que se transmite de persona a persona por el aire, generalmente cuando una persona con TB pulmonar activa:

* Tose
* Estornuda
* Habla
* Escupe

Al inhalar estas gotitas contaminadas, otra persona puede infectarse.
**Factores de riesgo**  

Aunque cualquiera puede infectarse, hay ciertos factores que aumentan el riesgo:

* Tener un sistema inmunológico debilitado (por VIH, diabetes, tratamientos con esteroides o quimioterapia)
* Desnutrición
* Vivir o trabajar en lugares cerrados y con poca ventilación
* Ser fumador
* Consumo excesivo de alcohol o drogas
* Vivir en zonas con alta prevalencia de TB

**Tipos de tuberculosis**  
1. **TB latente**: La bacteria está en el cuerpo pero no causa síntomas y no es contagiosa.
2. **TB activa**: La bacteria se multiplica y causa síntomas y puede transmitirse a otros.

**en que continentes se han visto mas casos**

| Continente / Región                   | % casos nuevos TB (2023) |
|--------------------------------------|---------------------------|
| Asia (Sur y Sudeste)                 | ≈ 45 %                    |
| África                               | ≈ 24 %                    |
| Pacífico Occidental (incl. China)    | ≈ 17 %                    |
| Oriente Medio / Mediterráneo         | ≈ 8 %                     |
| Américas                              | ≈ 3 %                     |
| Europa                               | ≈ 2 %                     |

**Existe una diferencia significativa entre mujeres y hombres**
| Sexo     | % de casos nuevos (2023) |
|----------|---------------------------|
| Hombres  | 55 %                      |
| Mujeres  | 33 %                      |


**¿Por qué ocurre esto?**
Varias posibles causas:

* Los hombres tienden a buscar atención médica más tarde, lo que retrasa el diagnóstico
* Factores de riesgo más comunes en hombres, como tabaquismo y consumo de alcohol, aumentan su vulnerabilidad .
* Ocupaciones con exposición elevada (como minería o trabajos en espacios cerrados) también hacen suponer mayor exposición en hombres .
* También hay discusión sobre diferencias biológicas que podrían influir en la susceptibilidad .

**metodos de diagnostico**

| Abreviatura | Significado                    | Explicación sencilla                                                                                   |
| ----------- | ------------------------------ | ----------------------------------------------------------------------------------------------------- |
| **rel**     | Recaída                        | La persona tuvo tuberculosis antes y la enfermedad volvió a aparecer. Se detecta con exámenes médicos.|
| **sn**      | Baciloscopia pulmonar negativa | No se ven bacterias en la muestra de pulmón al microscopio, pero puede haber tuberculosis; se hacen más pruebas para estar seguros. |
| **sp**      | Baciloscopia pulmonar positiva | Se ven bacterias en la muestra de pulmón al microscopio; es un caso típico y se empieza tratamiento.  |
| **ep**      | Extrapulmonar                  | La tuberculosis está en otras partes del cuerpo fuera del pulmón; el diagnóstico es más complicado y usa varios exámenes. |
            

**tipos de tratamiento**
**1. Tuberculosis sensible a fármacos (TB DS)**
- **Duración:** 6 meses
- **Fases:**
  - Fase intensiva (2 meses): Rifampicina, Isoniazida, Pirazinamida, Etambutol (RHZE)
  - Fase de continuación (4 meses): Rifampicina e Isoniazida (RH)
- Tratamiento estándar recomendado por la OMS.

**2. Tuberculosis multirresistente (MDR-TB)**
- Resistencia a rifampicina e isoniazida.
- **Duración:** 6 a 20 meses o más.
- Uso de medicamentos de segunda línea como bedaquilina, linezolid, levofloxacino, delamanid, entre otros.
- Requiere monitoreo riguroso.

**3. Tuberculosis extensivamente resistente (XDR-TB)**
- Resistente a rifampicina, isoniazida y a los medicamentos de segunda línea más importantes.
- Tratamientos más largos y complejos.
- Alta tasa de fracaso terapéutico y mortalidad.

**Índices de muertes por tuberculosis (estimaciones globales)**

| Año   | Muertes estimadas (millones) | Observaciones                         |
|-------|------------------------------|-------------------------------------|
| 2021  | ≈1.4 millones                | TB es una de las principales causas infecciosas de muerte. |
| 2023  | Datos preliminares indican leve descenso, pero sigue siendo alta la mortalidad en regiones con TB-MDR y coinfección con VIH. |

- La mayoría de las muertes ocurren en Asia del Sur, África Subsahariana y en personas con coinfección VIH.
- La mortalidad es mayor en casos de TB resistente debido a tratamiento más difícil.

# Manipulacion de datos

**Acerca de los datos**  

Un conjunto de datos del Informe Global sobre Tuberculosis de la Organización Mundial de la Salud (OMS), junto con datos de poblaciones globales.
El conjunto utiliza los códigos originales de la OMS.

Los nombres de las columnas de la columna 5 a la 60 se forman combinando *new_* con:

*   El método de diagnóstico (*rel* = recaída, *sn* = esputo pulmonar negativo, *sp* = esputo pulmonar positivo, *ep* = extrapulmonar).

*   El género (*f* = femenino, *m* = masculino).

*   El grupo de edad (*014* = 0 a 14 años, *1524* = 15 a 24, *2534* = 25 a 34, *3544* = 35 a 44, *4554* = 45 a 54, *5564* = 55 a 64, *65* = 65 años o más).

In [5]:
who.columns

Index(['country', 'iso2', 'iso3', 'year', 'new_sp_m014', 'new_sp_m1524',
       'new_sp_m2534', 'new_sp_m3544', 'new_sp_m4554', 'new_sp_m5564',
       'new_sp_m65', 'new_sp_f014', 'new_sp_f1524', 'new_sp_f2534',
       'new_sp_f3544', 'new_sp_f4554', 'new_sp_f5564', 'new_sp_f65',
       'new_sn_m014', 'new_sn_m1524', 'new_sn_m2534', 'new_sn_m3544',
       'new_sn_m4554', 'new_sn_m5564', 'new_sn_m65', 'new_sn_f014',
       'new_sn_f1524', 'new_sn_f2534', 'new_sn_f3544', 'new_sn_f4554',
       'new_sn_f5564', 'new_sn_f65', 'new_ep_m014', 'new_ep_m1524',
       'new_ep_m2534', 'new_ep_m3544', 'new_ep_m4554', 'new_ep_m5564',
       'new_ep_m65', 'new_ep_f014', 'new_ep_f1524', 'new_ep_f2534',
       'new_ep_f3544', 'new_ep_f4554', 'new_ep_f5564', 'new_ep_f65',
       'newrel_m014', 'newrel_m1524', 'newrel_m2534', 'newrel_m3544',
       'newrel_m4554', 'newrel_m5564', 'newrel_m65', 'newrel_f014',
       'newrel_f1524', 'newrel_f2534', 'newrel_f3544', 'newrel_f4554',
       'newrel_f5564', 'newrel_f65'],
      dtype='object')

In [6]:
population.columns

Index(['country', 'year', 'population'], dtype='object')

# Valores Nulos

In [11]:
who.isna().sum()

country            0
iso2               0
iso3               0
year               0
new_sp_m014     4067
new_sp_m1524    4031
new_sp_m2534    4034
new_sp_m3544    4021
new_sp_m4554    4017
new_sp_m5564    4022
new_sp_m65      4031
new_sp_f014     4066
new_sp_f1524    4046
new_sp_f2534    4040
new_sp_f3544    4041
new_sp_f4554    4036
new_sp_f5564    4045
new_sp_f65      4043
new_sn_m014     6195
new_sn_m1524    6210
new_sn_m2534    6218
new_sn_m3544    6215
new_sn_m4554    6213
new_sn_m5564    6219
new_sn_m65      6220
new_sn_f014     6200
new_sn_f1524    6218
new_sn_f2534    6224
new_sn_f3544    6220
new_sn_f4554    6222
new_sn_f5564    6223
new_sn_f65      6221
new_ep_m014     6202
new_ep_m1524    6214
new_ep_m2534    6220
new_ep_m3544    6216
new_ep_m4554    6220
new_ep_m5564    6225
new_ep_m65      6222
new_ep_f014     6208
new_ep_f1524    6219
new_ep_f2534    6219
new_ep_f3544    6219
new_ep_f4554    6223
new_ep_f5564    6223
new_ep_f65      6226
newrel_m014     7050
newrel_m1524    7058
newrel_m2534    7057
newrel_m3544    7056
newrel_m4554    7056
newrel_m5564    7055
newrel_m65      7058
newrel_f014     7050
newrel_f1524    7056
newrel_f2534    7058
newrel_f3544    7057
newrel_f4554    7057
newrel_f5564    7057
newrel_f65      7055
dtype: int64

In [9]:
# Filtrar valores faltantes
who[who.iso2.isna()]

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
4369,Namibia,NaN,NAM,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4370,Namibia,NaN,NAM,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4371,Namibia,NaN,NAM,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4372,Namibia,NaN,NAM,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4373,Namibia,NaN,NAM,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4374,Namibia,NaN,NAM,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,Namibia,NaN,NAM,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4376,Namibia,NaN,NAM,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,Namibia,NaN,NAM,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4378,Namibia,NaN,NAM,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4379,Namibia,NaN,NAM,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,Namibia,NaN,NAM,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,Namibia,NaN,NAM,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,Namibia,NaN,NAM,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,Namibia,NaN,NAM,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,Namibia,NaN,NAM,1995,0.0,68.0,235.0,113.0,55.0,21.0,6.0,5.0,49.0,78.0,50.0,16.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Namibia,NaN,NAM,1996,16.0,205.0,613.0,472.0,230.0,137.0,101.0,17.0,249.0,330.0,245.0,87.0,72.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4386,Namibia,NaN,NAM,1997,18.0,232.0,791.0,479.0,296.0,161.0,93.0,23.0,249.0,401.0,275.0,104.0,56.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4387,Namibia,NaN,NAM,1998,21.0,270.0,816.0,541.0,267.0,148.0,111.0,34.0,300.0,536.0,310.0,117.0,62.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,Namibia,NaN,NAM,1999,20.0,247.0,908.0,613.0,260.0,135.0,110.0,25.0,339.0,540.0,336.0,114.0,77.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,Namibia,NaN,NAM,2000,18.0,269.0,874.0,665.0,300.0,147.0,81.0,16.0,352.0,654.0,348.0,161.0,76.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,Namibia,NaN,NAM,2001,20.0,322.0,993.0,732.0,318.0,150.0,116.0,32.0,394.0,729.0,404.0,168.0,91.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,Namibia,NaN,NAM,2002,19.0,301.0,1033.0,750.0,326.0,146.0,96.0,42.0,357.0,795.0,484.0,182.0,91.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,Namibia,NaN,NAM,2003,31.0,364.0,1109.0,838.0,419.0,196.0,108.0,47.0,451.0,927.0,571.0,216.0,108.0,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4393,Namibia,NaN,NAM,2004,31.0,319.0,1092.0,866.0,371.0,159.0,131.0,30.0,400.0,819.0,554.0,203.0,106.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4394,Namibia,NaN,NAM,2005,98.0,355.0,1027.0,874.0,365.0,146.0,120.0,105.0,399.0,809.0,525.0,213.0,95.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,Namibia,NaN,NAM,2006,86.0,347.0,1052.0,799.0,386.0,174.0,146.0,74.0,485.0,875.0,521.0,239.0,92.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4396,Namibia,NaN,NAM,2007,57.0,370.0,1018.0,786.0,346.0,149.0,120.0,69.0,417.0,826.0,513.0,242.0,102.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397,Namibia,NaN,NAM,2008,30.0,387.0,1033.0,757.0,346.0,149.0,132.0,73.0,466.0,702.0,437.0,226.0,110.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4398,Namibia,NaN,NAM,2009,41.0,357.0,936.0,689.0,348.0,166.0,121.0,84.0,384.0,678.0,407.0,214.0,97.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4399,Namibia,NaN,NAM,2010,36.0,359.0,852.0,680.0,287.0,146.0,126.0,67.0,429.0,685.0,382.0,206.0,122.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4400,Namibia,NaN,NAM,2011,48.0,337.0,844.0,660.0,361.0,152.0,138.0,78.0,427.0,653.0,410.0,185.0,100.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4401,Namibia,NaN,NAM,2012,61.0,358.0,810.0,686.0,292.0,157.0,137.0,81.0,394.0,582.0,396.0,198.0,84.0,97.0,386.0,153.0,477.0,516.0,268.0,162.0,135.0,339.0,200.0,379.0,306.0,183.0,98.0,90.0,180.0,126.0,228.0,261.0,138.0,46.0,55.0,163.0,116.0,219.0,177.0,84.0,25.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4402,Namibia,NaN,NAM,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,612.0,1496.0,1404.0,723.0,392.0,309.0,491.0,688.0,1137.0,747.0,408.0,220.0,202.0

In [10]:
# Los valores faltantes de iso2 para Namibia se llenan con un string "NA"
who.loc[who.country == "Namibia", "iso2"] = "NA"

In [12]:
# Todos los valores faltantes de todas las columnas vab a ser rellenadas con un valor 0
who = who.fillna(0)

In [13]:
# population tiene varios faltantes?
population.isna().sum()

country       0
year          0
population    0
dtype: int64

# Modificar la estructura de los datos

In [14]:
who.head()

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,Afghanistan,AF,AFG,1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AF,AFG,1981,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AF,AFG,1982,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AF,AFG,1983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AF,AFG,1984,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
population.head()

       country  year  population
0  Afghanistan  1995    17586073
1  Afghanistan  1996    18415307
2  Afghanistan  1997    19021226
3  Afghanistan  1998    19496836
4  Afghanistan  1999    19987071

In [17]:
# Convertir las columnas despues de iso3 en filas
who2 = who.melt(id_vars=["country", "year", "iso2", "iso3"])
who2.head(10)

       country  year iso2 iso3     variable  value
0  Afghanistan  1980   AF  AFG  new_sp_m014    0.0
1  Afghanistan  1981   AF  AFG  new_sp_m014    0.0
2  Afghanistan  1982   AF  AFG  new_sp_m014    0.0
3  Afghanistan  1983   AF  AFG  new_sp_m014    0.0
4  Afghanistan  1984   AF  AFG  new_sp_m014    0.0
5  Afghanistan  1985   AF  AFG  new_sp_m014    0.0
6  Afghanistan  1986   AF  AFG  new_sp_m014    0.0
7  Afghanistan  1987   AF  AFG  new_sp_m014    0.0
8  Afghanistan  1988   AF  AFG  new_sp_m014    0.0
9  Afghanistan  1989   AF  AFG  new_sp_m014    0.0

In [18]:
# Añadir la columna que indica el genero
who2["gender"] = np.where(who2["variable"].str.contains("m"),"masculino","femenino")
who2.head(100)

        country  year iso2 iso3     variable  value     gender
0   Afghanistan  1980   AF  AFG  new_sp_m014    0.0  masculino
1   Afghanistan  1981   AF  AFG  new_sp_m014    0.0  masculino
2   Afghanistan  1982   AF  AFG  new_sp_m014    0.0  masculino
3   Afghanistan  1983   AF  AFG  new_sp_m014    0.0  masculino
4   Afghanistan  1984   AF  AFG  new_sp_m014    0.0  masculino
5   Afghanistan  1985   AF  AFG  new_sp_m014    0.0  masculino
6   Afghanistan  1986   AF  AFG  new_sp_m014    0.0  masculino
7   Afghanistan  1987   AF  AFG  new_sp_m014    0.0  masculino
8   Afghanistan  1988   AF  AFG  new_sp_m014    0.0  masculino
9   Afghanistan  1989   AF  AFG  new_sp_m014    0.0  masculino
10  Afghanistan  1990   AF  AFG  new_sp_m014    0.0  masculino
11  Afghanistan  1991   AF  AFG  new_sp_m014    0.0  masculino
12  Afghanistan  1992   AF  AFG  new_sp_m014    0.0  masculino
13  Afghanistan  1993   AF  AFG  new_sp_m014    0.0  masculino
14  Afghanistan  1994   AF  AFG  new_sp_m014    0.0  masculino
15  Afghanistan  1995   AF  AFG  new_sp_m014    0.0  masculino
16  Afghanistan  1996   AF  AFG  new_sp_m014    0.0  masculino
17  Afghanistan  1997   AF  AFG  new_sp_m014    0.0  masculino
18  Afghanistan  1998   AF  AFG  new_sp_m014   30.0  masculino
19  Afghanistan  1999   AF  AFG  new_sp_m014    8.0  masculino
20  Afghanistan  2000   AF  AFG  new_sp_m014   52.0  masculino
21  Afghanistan  2001   AF  AFG  new_sp_m014  129.0  masculino
22  Afghanistan  2002   AF  AFG  new_sp_m014   90.0  masculino
23  Afghanistan  2003   AF  AFG  new_sp_m014  127.0  masculino
24  Afghanistan  2004   AF  AFG  new_sp_m014  139.0  masculino
25  Afghanistan  2005   AF  AFG  new_sp_m014  151.0  masculino
26  Afghanistan  2006   AF  AFG  new_sp_m014  193.0  masculino
27  Afghanistan  2007   AF  AFG  new_sp_m014  186.0  masculino
28  Afghanistan  2008   AF  AFG  new_sp_m014  187.0  masculino
29  Afghanistan  2009   AF  AFG  new_sp_m014  200.0  masculino
30  Afghanistan  2010   AF  AFG  new_sp_m014  197.0  masculino
31  Afghanistan  2011   AF  AFG  new_sp_m014  204.0  masculino
32  Afghanistan  2012   AF  AFG  new_sp_m014  188.0  masculino
33  Afghanistan  2013   AF  AFG  new_sp_m014    0.0  masculino
34      Albania  1980   AL  ALB  new_sp_m014    0.0  masculino
35      Albania  1981   AL  ALB  new_sp_m014    0.0  masculino
36      Albania  1982   AL  ALB  new_sp_m014    0.0  masculino
37      Albania  1983   AL  ALB  new_sp_m014    0.0  masculino
38      Albania  1984   AL  ALB  new_sp_m014    0.0  masculino
39      Albania  1985   AL  ALB  new_sp_m014    0.0  masculino
40      Albania  1986   AL  ALB  new_sp_m014    0.0  masculino
41      Albania  1987   AL  ALB  new_sp_m014    0.0  masculino
42      Albania  1988   AL  ALB  new_sp_m014    0.0  masculino
43      Albania  1989   AL  ALB  new_sp_m014    0.0  masculino
44      Albania  1990   AL  ALB  new_sp_m014    0.0  masculino
45      Albania  1991   AL  ALB  new_sp_m014    0.0  masculino
46      Albania  1992   AL  ALB  new_sp_m014    0.0  masculino
47      Albania  1993   AL  ALB  new_sp_m014    0.0  masculino
48      Albania  1994   AL  ALB  new_sp_m014    0.0  masculino
49      Albania  1995   AL  ALB  new_sp_m014    0.0  masculino
50      Albania  1996   AL  ALB  new_sp_m014    0.0  masculino
51      Albania  1997   AL  ALB  new_sp_m014    0.0  masculino
52      Albania  1998   AL  ALB  new_sp_m014    1.0  masculino
53      Albania  1999   AL  ALB  new_sp_m014    0.0  masculino
54      Albania  2000   AL  ALB  new_sp_m014    2.0  masculino
55      Albania  2001   AL  ALB  new_sp_m014    3.0  masculino
56      Albania  2002   AL  ALB  new_sp_m014    0.0  masculino
57      Albania  2003   AL  ALB  new_sp_m014    0.0  masculino
58      Albania  2004   AL  ALB  new_sp_m014    5.0  masculino
59      Albania  2005   AL  ALB  new_sp_m014    0.0  masculino
60      Albania  2006   AL  ALB  new_sp_m014    5.0  masculino
61      Albania  2007   AL  ALB  new_sp_m014    0.0  masculino
62      Albania  2008   AL  ALB  new_sp_m014    1.0  masculino
63      Albania  2009   AL  ALB  new_sp_m014    0.0  masculino
64      Albania  2010   AL  ALB  new_sp_m014    0.0  masculino
65      Albania  2011   AL  ALB  new_sp_m014    0.0  masculino
66      Albania  2012   AL  ALB  new_sp_m014    0.0  masculino
67      Albania  2013   AL  ALB  new_sp_m014    0.0  masculino
68      Algeria  1980   DZ  DZA  new_sp_m014    0.0  masculino
69      Algeria  1981   DZ  DZA  new_sp_m014    0.0  masculino
70      Algeria  1982   DZ  DZA  new_sp_m014    0.0  masculino
71      Algeria  1983   DZ  DZA  new_sp_m014    0.0  masculino
72      Algeria  1984   DZ  DZA  new_sp_m014    0.0  masculino
73      Algeria  1985   DZ  DZA  new_sp_m014    0.0  masculino
74      Algeria  1986   DZ  DZA  new_sp_m014    0.0  masculino
75      Algeria  1987   DZ  DZA  new_sp_m014    0.0  masculino
76      Algeria  1988   DZ  DZA  new_sp_m014    0.0  masculino
77      Algeria  1989   DZ  DZA  new_sp_m014    0.0  masculino
78      Algeria  1990   DZ  DZA  new_sp_m014    0.0  masculino
79      Algeria  1991   DZ  DZA  new_sp_m014    0.0  masculino
80      Algeria  1992   DZ  DZA  new_sp_m014    0.0  masculino
81      Algeria  1993   DZ  DZA  new_sp_m014    0.0  masculino
82      Algeria  1994   DZ  DZA  new_sp_m014    0.0  masculino
83      Algeria  1995   DZ  DZA  new_sp_m014    0.0  masculino
84      Algeria  1996   DZ  DZA  new_sp_m014    0.0  masculino
85      Algeria  1997   DZ  DZA  new_sp_m014  659.0  masculino
86      Algeria  1998   DZ  DZA  new_sp_m014    0.0  masculino
87      Algeria  1999   DZ  DZA  new_sp_m014   40.0  masculino
88      Algeria  2000   DZ  DZA  new_sp_m014   59.0  masculino
89      Algeria  2001   DZ  DZA  new_sp_m014   41.0  masculino
90      Algeria  2002   DZ  DZA  new_sp_m014   39.0  masculino
91      Algeria  2003   DZ  DZA  new_sp_m014   40.0  masculino
92      Algeria  2004   DZ  DZA  new_sp_m014   63.0  masculino
93      Algeria  2005   DZ  DZA  new_sp_m014   53.0  masculino
94      Algeria  2006   DZ  DZA  new_sp_m014   41.0  masculino
95      Algeria  2007   DZ  DZA  new_sp_m014   95.0  masculino
96      Algeria  2008   DZ  DZA  new_sp_m014   99.0  masculino
97      Algeria  2009   DZ  DZA  new_sp_m014   43.0  masculino
98      Algeria  2010   DZ  DZA  new_sp_m014   52.0  masculino
99      Algeria  2011   DZ  DZA  new_sp_m014   42.0  masculino

In [19]:
# funcion para asignar el grupo de edad
def asignar_groupedad(valor):
  if "014" in valor:
     return "0-14"
  elif "1524" in valor:
    return "15-24"
  elif "25-34" in valor:
    return "25-34"
  elif "3544" in valor:
    return "35-44"
  elif "4554" in valor:
    return "45-54"
  elif "5564" in valor:
    return "55-64"
  elif "65" in valor:
    return "65+"

In [20]:
who2["agegroup"] = who2["variable"].apply(asignar_groupedad)
who2.head()

       country  year iso2 iso3     variable  value     gender agegroup
0  Afghanistan  1980   AF  AFG  new_sp_m014    0.0  masculino     0-14
1  Afghanistan  1981   AF  AFG  new_sp_m014    0.0  masculino     0-14
2  Afghanistan  1982   AF  AFG  new_sp_m014    0.0  masculino     0-14
3  Afghanistan  1983   AF  AFG  new_sp_m014    0.0  masculino     0-14
4  Afghanistan  1984   AF  AFG  new_sp_m014    0.0  masculino     0-14

In [21]:
# funcion para asignar los metodos de diagnóstico
def asignar_metodo(valor):
  if "rel" in valor:
    return "recaida"
  if "sn" in valor:
    return "esputo pulmonar negativo"
  if "sp" in valor:
    return "esputo pulmonar positivo"
  if "ep" in valor:
    return "extrapulmonar"

In [22]:
#asignar la funcion a una columna
who2["method"] = who2["variable"].apply(asignar_metodo)
who2.head()

,country,year,iso2,iso3,variable,value,gender,agegroup,method
0,Afghanistan,1980,AF,AFG,new_sp_m014,0.0,masculino,0-14,esputo pulmonar positivo
1,Afghanistan,1981,AF,AFG,new_sp_m014,0.0,masculino,0-14,esputo pulmonar positivo
2,Afghanistan,1982,AF,AFG,new_sp_m014,0.0,masculino,0-14,esputo pulmonar positivo
3,Afghanistan,1983,AF,AFG,new_sp_m014,0.0,masculino,0-14,esputo pulmonar positivo
4,Afghanistan,1984,AF,AFG,new_sp_m014,0.0,masculino,0-14,esputo pulmonar positivo

In [23]:
#eliminar la columna variable que ya no me sirve
who2 = who2.drop(columns=["variable"])

In [24]:
who2.head()

,country,year,iso2,iso3,value,gender,agegroup,method
0,Afghanistan,1980,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
1,Afghanistan,1981,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
2,Afghanistan,1982,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
3,Afghanistan,1983,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
4,Afghanistan,1984,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo

In [25]:
who2 = who2.rename(columns={"value":"cases"})

In [26]:
who2.head()

,country,year,iso2,iso3,cases,gender,agegroup,method
0,Afghanistan,1980,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
1,Afghanistan,1981,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
2,Afghanistan,1982,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
3,Afghanistan,1983,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo
4,Afghanistan,1984,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo

In [27]:
# vamos a realizar un join con population
df = pd.merge(left=who2, right=population, how="inner", on=["country", "year"])
df.head(100)

,country,year,iso2,iso3,cases,gender,agegroup,method,population
0,Afghanistan,1995,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,17586073
1,Afghanistan,1996,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,18415307
2,Afghanistan,1997,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,19021226
3,Afghanistan,1998,AF,AFG,30.0,masculino,0-14,esputo pulmonar positivo,19496836
4,Afghanistan,1999,AF,AFG,8.0,masculino,0-14,esputo pulmonar positivo,19987071
5,Afghanistan,2000,AF,AFG,52.0,masculino,0-14,esputo pulmonar positivo,20595360
6,Afghanistan,2001,AF,AFG,129.0,masculino,0-14,esputo pulmonar positivo,21347782
7,Afghanistan,2002,AF,AFG,90.0,masculino,0-14,esputo pulmonar positivo,22202806
8,Afghanistan,2003,AF,AFG,127.0,masculino,0-14,esputo pulmonar positivo,23116142
9,Afghanistan,2004,AF,AFG,139.0,masculino,0-14,esputo pulmonar positivo,24018682
10,Afghanistan,2005,AF,AFG,151.0,masculino,0-14,esputo pulmonar positivo,24860855
11,Afghanistan,2006,AF,AFG,193.0,masculino,0-14,esputo pulmonar positivo,25631282
12,Afghanistan,2007,AF,AFG,186.0,masculino,0-14,esputo pulmonar positivo,26349243
13,Afghanistan,2008,AF,AFG,187.0,masculino,0-14,esputo pulmonar positivo,27032197
14,Afghanistan,2009,AF,AFG,200.0,masculino,0-14,esputo pulmonar positivo,27708187
15,Afghanistan,2010,AF,AFG,197.0,masculino,0-14,esputo pulmonar positivo,28397812
16,Afghanistan,2011,AF,AFG,204.0,masculino,0-14,esputo pulmonar positivo,29105480
17,Afghanistan,2012,AF,AFG,188.0,masculino,0-14,esputo pulmonar positivo,29824536
18,Afghanistan,2013,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,30551674
19,Albania,1995,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3357858
20,Albania,1996,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3341043
21,Albania,1997,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3331317
22,Albania,1998,AL,ALB,1.0,masculino,0-14,esputo pulmonar positivo,3325456
23,Albania,1999,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3317941
24,Albania,2000,AL,ALB,2.0,masculino,0-14,esputo pulmonar positivo,3304948
25,Albania,2001,AL,ALB,3.0,masculino,0-14,esputo pulmonar positivo,3286084
26,Albania,2002,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3263596
27,Albania,2003,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3239385
28,Albania,2004,AL,ALB,5.0,masculino,0-14,esputo pulmonar positivo,3216197
29,Albania,2005,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3196130
30,Albania,2006,AL,ALB,5.0,masculino,0-14,esputo pulmonar positivo,3179573
31,Albania,2007,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3166222
32,Albania,2008,AL,ALB,1.0,masculino,0-14,esputo pulmonar positivo,3156608
33,Albania,2009,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3151185
34,Albania,2010,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3150143
35,Albania,2011,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3153883
36,Albania,2012,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3162083
37,Albania,2013,AL,ALB,0.0,masculino,0-14,esputo pulmonar positivo,3173271
38,Algeria,1995,DZ,DZA,0.0,masculino,0-14,esputo pulmonar positivo,29315463
39,Algeria,1996,DZ,DZA,0.0,masculino,0-14,esputo pulmonar positivo,29845208
40,Algeria,1997,DZ,DZA,659.0,masculino,0-14,esputo pulmonar positivo,30345466
41,Algeria,1998,DZ,DZA,0.0,masculino,0-14,esputo pulmonar positivo,30820435
42,Algeria,1999,DZ,DZA,40.0,masculino,0-14,esputo pulmonar positivo,31276295
43,Algeria,2000,DZ,DZA,59.0,masculino,0-14,esputo pulmonar positivo,31719449
44,Algeria,2001,DZ,DZA,41.0,masculino,0-14,esputo pulmonar positivo,32150198
45,Algeria,2002,DZ,DZA,39.0,masculino,0-14,esputo pulmonar positivo,32572977
46,Algeria,2003,DZ,DZA,40.0,masculino,0-14,esputo pulmonar positivo,33003442
47,Algeria,2004,DZ,DZA,63.0,masculino,0-14,esputo pulmonar positivo,33461345
48,Algeria,2005,DZ,DZA,53.0,masculino,0-14,esputo pulmonar positivo,33960903
49,Algeria,2006,DZ,DZA,41.0,masculino,0-14,esputo pulmonar positivo,34507214
50,Algeria,2007,DZ,DZA,95.0,masculino,0-14,esputo pulmonar positivo,35097043
51,Algeria,2008,DZ,DZA,99.0,masculino,0-14,esputo pulmonar positivo,35725377
52,Algeria,2009,DZ,DZA,43.0,masculino,0-14,esputo pulmonar positivo,36383302
53,Algeria,2010,DZ,DZA,52.0,masculino,0-14,esputo pulmonar positivo,37062820
54,Algeria,2011,DZ,DZA,42.0,masculino,0-14,esputo pulmonar positivo,37762962
55,Algeria,2012,DZ,DZA,29.0,masculino,0-14,esputo pulmonar positivo,38481705
56,Algeria,2013,DZ,DZA,0.0,masculino,0-14,esputo pulmonar positivo,39208194
57,American Samoa,1995,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,52874
58,American Samoa,1996,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,53926
59,American Samoa,1997,AS,ASM,1.0,masculino,0-14,esputo pulmonar positivo,54942
60,American Samoa,1998,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,55899
61,American Samoa,1999,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,56768
62,American Samoa,2000,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,57522
63,American Samoa,2001,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,58176
64,American Samoa,2002,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,58729
65,American Samoa,2003,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,59117
66,American Samoa,2004,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,59262
67,American Samoa,2005,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,59117
68,American Samoa,2006,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,58652
69,American Samoa,2007,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,57919
70,American Samoa,2008,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,57053
71,American Samoa,2009,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,56245
72,American Samoa,2010,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,55636
73,American Samoa,2011,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,55274
74,American Samoa,2012,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,55128
75,American Samoa,2013,AS,ASM,0.0,masculino,0-14,esputo pulmonar positivo,55165
76,Andorra,1995,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,63854
77,Andorra,1996,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,64274
78,Andorra,1997,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,64090
79,Andorra,1998,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,63799
80,Andorra,1999,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,64084
81,Andorra,2000,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,65399
82,Andorra,2001,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,68000
83,Andorra,2002,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,71639
84,Andorra,2003,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,75643
85,Andorra,2004,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,79060
86,Andorra,2005,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,81223
87,Andorra,2006,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,81877
88,Andorra,2007,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,81292
89,Andorra,2008,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,79969
90,Andorra,2009,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,78659
91,Andorra,2010,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,77907
92,Andorra,2011,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,77865
93,Andorra,2012,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,78360
94,Andorra,2013,AD,AND,0.0,masculino,0-14,esputo pulmonar positivo,79218
95,Angola,1995,AO,AGO,386.0,masculino,0-14,esputo pulmonar positivo,12104952
96,Angola,1996,AO,AGO,360.0,masculino,0-14,esputo pulmonar positivo,12451945
97,Angola,1997,AO,AGO,419.0,masculino,0-14,esputo pulmonar positivo,12791388
98,Angola,1998,AO,AGO,240.0,masculino,0-14,esputo pulmonar positivo,13137542
99,Angola,1999,AO,AGO,391.0,masculino,0-14,esputo pulmonar positivo,13510616

In [29]:
df.to_csv("tuberculosis.csv", index=False)

# Analisis exploratorio

In [30]:
df.head()

,country,year,iso2,iso3,cases,gender,agegroup,method,population
0,Afghanistan,1995,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,17586073
1,Afghanistan,1996,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,18415307
2,Afghanistan,1997,AF,AFG,0.0,masculino,0-14,esputo pulmonar positivo,19021226
3,Afghanistan,1998,AF,AFG,30.0,masculino,0-14,esputo pulmonar positivo,19496836
4,Afghanistan,1999,AF,AFG,8.0,masculino,0-14,esputo pulmonar positivo,19987071

In [33]:
# cantidad de paises y rango de fechas
print(f"Año de inicio: {df['year'].min()}")
print(f"Año de finalizacion: {df['year'].max()}")
print(f"Cantidad de paises: {df['country'].nunique()}")

Año de inicio: 1995
Año de finalizacion: 2013
Cantidad de paises: 217

In [39]:
by_method = df.groupby("method", as_index=False)["cases"].sum()
by_method["percent_of_total"] = 100 * by_method["cases"] / by_method["cases"].sum()
by_method

                     method       cases  percent_of_total
0  esputo pulmonar negativo   6279526.0         14.545284
1  esputo pulmonar positivo  31701213.0         73.429611
2             extrapulmonar   1986179.0          4.600592
3                   recaida   3205329.0          7.424513